import './categoryList';
import './createActivity';
import './componentKindList';
import './createActivityGroup';
import './updateActivity';
import './updateActivityGroup';
import './eduProgramId';
import './viewActivityData';
import './deleteRow';
