import { MfeRoutes } from './routes';

export enum EduPlanExposedRoutes {
  EDU_PLAN_INFO_ACTIVITY_INFO_ROOT = MfeRoutes.EDU_PLAN_INFO_ACTIVITY_INFO_ROOT,
  EDU_PLAN_INFO_ACTIVITY_VIEW = MfeRoutes.EDU_PLAN_INFO_ACTIVITY_VIEW,
  EDU_PLAN_INFO_ACTIVITY_LESSON_INFO = MfeRoutes.EDU_PLAN_INFO_ACTIVITY_LESSON_INFO,
  EDU_PLAN_INFO_ACTIVITY_SETTINGS_INFO = MfeRoutes.EDU_PLAN_INFO_ACTIVITY_SETTINGS_INFO,
  ACTIVITY_TOPIC_ROOT = MfeRoutes.ACTIVITY_TOPIC_ROOT,
  ACTIVITY_TOPIC_ITEM_CREATE = MfeRoutes.ACTIVITY_TOPIC_ITEM_CREATE,
  ACTIVITY_TOPIC_GROUP_CREATE = MfeRoutes.ACTIVITY_TOPIC_GROUP_CREATE,
  ACTIVITY_TOPIC_GROUP_OR_ITEM_EDIT = MfeRoutes.ACTIVITY_TOPIC_GROUP_OR_ITEM_EDIT,
  LESSON_INFO_ROOT = MfeRoutes.LESSON_INFO_ROOT,
  LESSON_INFO_CONTENT = MfeRoutes.LESSON_INFO_CONTENT,
  LESSON_INFO_CONTENT_CONSTRUCTOR = MfeRoutes.LESSON_INFO_CONTENT_CONSTRUCTOR,
}
