export { getGrouppedLessonKindsQuery } from './getGrouppedLessonKindsQuery';
export { getActivityTopicNodesQuery } from './getActivityTopicNodesQuery';
export { getEffortUnitSettingsQuery } from './getEffortUnitSettingsQuery';
export { getSpaceIdByActivityIdQuery } from './getSpaceIdByActivityIdQuery';
export { getActivityPartTypesQuery } from './getActivityPartTypesQuery';
export { getActivityComponentKindsQuery } from './getActivityComponentKindsQuery';
export { getActivityTopicGroupOrItemQuery } from './getActivityTopicGroupOrItemQuery';
export { deleteTopicRowMutation } from './deleteTopicRowMutation';
export { switchActivityRowsPriorityMutation } from './switchActivityRowsPriorityMutation';
